# Site settings
title: CodeTravel
email: hello@erikathea.com
description: > # this means to ignore newlines until "baseurl:"
  Dev. Backpacker. Storyteller. Dreamer. Personal site of Erika Thea.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://erikathea.com" # the base hostname & protocol for your site
twitter_username: erikathea
github_username:  erikathea
disqus: codetravel

jekyll-mentions: https://twitter.com

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Front-Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "thea"
