---
title: CodeTravel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: erikathea
email: hello@erikathea.com
description: Dev. Backpacker. Storyteller. Dreamer. Personal site of Erika Thea.
baseurl: 
url: https://erikathea.com
enforce_ssl: www.erikathea.com
twitter_username: erikathea
github_username: erikathea
disqus: codetravel
owner: erikathea
jekyll-mentions: https://twitter.com
markdown: kramdown
highlighter: rouge
permalink: "/blog/:title/"
sass:
  sass_dir: assets/stylesheets
  style: compressed
gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
paginate: 5
paginate_path: "/blog/:num/"
